services:
  web:
    image: miphp
    build: ./web
    container_name: php
    ports:
      - "8080:80"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DRIVER: pgsql
    volumes:
      - ./web:/var/www/html
    restart: unless-stopped
  db:
    image: postgres:17-alpine
    container_name: postgres
    command: postgres -p ${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./db/pgsql:/docker-entrypoint-initdb.d