name: zonavet
services: 
  proxy:
    image: nginx:alpine    
    restart: unless-stopped
    container_name: zonavetproxy
    ports:
      - "80:80"
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - front
  frontend:
    container_name: zonavetfront
    build:
      context: ./frontend
      target: development
    restart: unless-stopped
    user:  node
    working_dir : "/frontend"
    command: "npm i && npm start"
    tty : true
    volumes : 
      - ./frontend:/frontend
      - /frontend/node_modules
    networks:
      - front
  backend:
    build:
      context: ./backend
      target: development
    container_name: zonavetback
    user: laravel
    tty: true
    command: sh -c "composer install  && php artisan migrate --seed && composer run dev"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/var/www/html
      - /var/www/html/vendor
    restart: unless-stopped
    ports:
      - 8000:8000
    networks: 
      - front
      - back
  db:
    image: postgres:17-alpine
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    networks: 
      - back
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${DB_USERNAME} -d $${DB_DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 5

networks: 
  front:
    driver: bridge
  back:
    driver: bridge