name: zonavet
services: 
  proxy:
    image: nginx:alpine    
    restart: unless-stopped
    container_name: zonavetproxy
    ports:
      - "80:80"
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - front
  frontend:
    container_name: zonavetfront
    build:
      context: ./frontend
      target: development
    restart: unless-stopped
    user:  node
    working_dir : "/frontend"
    command: sh -c "npm i && npm start"
    tty : true
    volumes : 
      - ./frontend:/frontend
      - zonavetnode_modules:/frontend/node_modules 
      - zonavet.angular:/frontend/.angular          
    networks:
      - front
  backend:
    build:
      context: ./backend
      target: development
    container_name: zonavetback
    user: laravel
    tty: true
    command: sh -c "composer install  && php artisan migrate --seed && composer run dev"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/var/www/html
      - zonavetvendor:/var/www/html/vendor
    restart: unless-stopped
    ports:
      - 8000:8000
    networks: 
      - front
      - back
  db:
    image: postgres:17-alpine
    container_name: zonavetdb
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    networks: 
      - back
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${DB_USERNAME} -d $${DB_DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 5

networks: 
  front:
    driver: bridge
  back:
    driver: bridge

# Hacemos volumenes nombrados para que las dependencias no se almacenen en local
# No se creen nuevos volumenes cada vez que levantamos los contenedoresPero que los podemos 
# Pero que los podamos borrar con docker volume prune (borra todos los volumenes que haya)
# Esta forma es más eficiente que tener node_modules en el host, sobre todo si es una carpeta
# en el sistema de archivos de windows.
volumes:
  zonavetnode_modules: # Definir el volumen aquí lo hace persistente
  zonavet.angular:     # Lo mismo para la caché de Angular
  zonavetvendor:       # Lo mismo para vendor del backend.